# Define screen
SCREEN_HEIGHT = 320
SCREEN_WIDTH = 480
SCREEN_BORDERLESS = True

# Define cell size and related values
CELL_SIZE = 20
CELL_WALL_THICKNESS = 2
CELL_BODY_SIZE = CELL_SIZE - 2 * CELL_WALL_THICKNESS
CELL_START_SE_WALLS = CELL_WALL_THICKNESS + CELL_BODY_SIZE
CELL_ARRAY_ROW_LENGTH = int(SCREEN_WIDTH / CELL_SIZE)

# Define Colors
COLOR_SEARCHING = "YELLOW"
COLOR_SEARCHED = "ORANGE"
COLOR_PATH = "BLUE"
COLOR_WALLS = "BLACK"
COLOR_CELL = "WHITE"
COLOR_START = "BLUE"
COLOR_GOAL = "RED"

# Define Waiting times
SLEEP_SEARCH = 0.1
SLEEP_MAZE_GEN = 0.05
SLEEP_START_SEARCH = 1